# Generated by Django 4.1.5 on 2023-01-06 16:56

from django.db import migrations, models
import django_b2.storage


class Migration(migrations.Migration):

    dependencies = [
        ('Django_BackBlaze2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=django_b2.storage.B2Storage()),
        ),
    ]
